server:
  port: 9090
spring:
  security:
    oauth2:
      client:
        registration:
          #google...
          keycloak:
            #credenciais do cliente oauth2 cadastrado no keycloak
            client-id: spring-security-keycloak
            client-secret: kBirAFbmPtvHjpUXzFikIL8xqnBkShjL
            scope: openid, profile, email
        provider:
          #cliente oauth apontando para o keycloak
          keycloak:
            issuer-uri: http://localhost:8080/realms/ifsc
      resourceserver:
        jwt:
          #issuer-uri: https://accounts.google.com
          #keycloak
          issuer-uri: http://localhost:8080/realms/ifsc